services:
  - type: web
    name: koçluk-platformu
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        value: sk_test_...  # kendi Stripe anahtarınla değiştir
      - key: ZOOM_JWT_TOKEN
        value: eyJhbGciOi...  # kendi Zoom JWT token'ınla değiştir
